train_mode: train
loss_type: ll
learner: adam
learning_rate: 0.001
l2_norm: 0
weight_decay: 1e-4
max_epochs: 100
eval_step: 1
clip_grad_norm: {'max_norm': 5, 'norm_type': 2}
train_batch_size: 1024
eval_batch_size: 1024
device: 'cuda:1'
checkpoint_dir: saved_models/ind
eval_mode: point
list_len: 50
topks: [1,5,10]
num_trials: 2
continue_metric: AUC
eval_metric_bigger: True
seed: 1111
reproducibility: False
counterfactual_debias: False
alpha: 0.1
c: 10

tags_num: 1
have_es: False
batch_neg_size: 5


user_f_pos: [0]
item_f_pos: [1,2,3]
domain_f_pos: [4]
hist_max_len: 5

have_hist: True

# train_set: data/Cloud_Theme/feateng_data/input_data/train_set2.pkl
train_set: data/Cloud_Theme/feateng_data/input_data/train_d3.pkl


# test_set: data/Cloud_Theme/feateng_data/input_data/test_set2.pkl
test_set: data/Cloud_Theme/feateng_data/input_data/test_d3.pkl


# ckpt_file: None
ckpt_file: saved_models/ind/ncf-Cloud-Jun-02-2023_00-48-16.pth
# ckpt_file: saved_models/ind/aesm2-Cloud-Apr-23-2023_14-54-58.pth
# ckpt_file: saved_models/ind/m2m-Cloud-May-04-2023_13-11-18.pth

# ckpt_file: saved_models/ind/mmoe-Cloud-Apr-20-2023_00-58-23.pth
# ckpt_file: saved_models/ind/m_scan_debias-Cloud-Apr-20-2023_20-55-04.pth
# ckpt_file: saved_models/ind/ple-Cloud-May-04-2023_13-45-36.pth
# ckpt_file: saved_models/ind/shared_bottom-Cloud-Apr-20-2023_01-04-23.pth
#ckpt_file: saved_models/ind/ncf_debias-Cloud-Nov-24-2022_08-39-48.pth
#ckpt_file: saved_models/ind/ncf-Cloud-Nov-24-2022_08-35-51.pth

gauc: False

