Cloud: {
  model_name: dcn,
  embed_dim: 64,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True
}

aliccp: {
  model_name: dcn,
  embed_dim: 32,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True
}