zj: {
  model_name: dien,
  embed_dim: 64,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True,
  gru_h_dim: 64,
  lamda1: 1,
}

lastfm: {
  model_name: dien,
  embed_dim: 64,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True,
  gru_h_dim: 64,
  lamda1: 1,
}

hvideo: {
  model_name: dien,
  embed_dim: 64,
  hidden_dims: [200, 80],
  dropout: 0.2,
  use_hist: True,
  gru_h_dim: 64,
  lamda1: 1,
}