
aliccp: {
  model_name: m2m,
  embed_dim: 32,
  hidden_dims: [512, 256],
  meta_dims: [128,64],
  dropout: 0.2,
  use_hist: True,
  expert_num: 3,
  task_num: 1,
}

Cloud: {
  model_name: mmoe,
  embed_dim: 32,
  hidden_dims: [512, 256],
  meta_dims: [128,64],
  dropout: 0.2,
  use_hist: True,
  expert_num: 3,
  task_num: 1,
}
