
aliccp: {
  model_name: aliccp,
  embed_dim: 32,
  hidden_dims: [512, 256],
  tower_dims: [128,64],
  dropout: 0.2,
  use_hist: True,
  task_num: 3,
}

Cloud: {
  model_name: aliccp,
  embed_dim: 32,
  hidden_dims: [512, 256],
  tower_dims: [128,64],
  dropout: 0.2,
  use_hist: True,
  task_num: 1,
}
